// samples/web/vuejs/src/App.vue
<script setup lang="ts">
/* NOTE: This is an EXAMPLE app page for controlling the state of the app. This is not required to use the web component.
          For integration example, please see face-vuejs/src/components/LivenessDetectorView.vue */

import { ref } from "vue";
import InitialView from "./components/InitialView.vue";
import LivenessDetectorView from "./components/LivenessDetectorView.vue";
import ResultView from "./components/ResultView.vue";
import RetryView from "./components/RetryView.vue";

type LivenessOperationMode = "Passive" | "PassiveActive";

const verifyImage = ref<File | undefined>(undefined);
const action = ref<"detectLiveness" | "detectLivenessWithVerify">(
  "detectLiveness"
);
const livenessDetectorState = ref<"Initial" | "LivenessDetector" | "Retry" | "Result">(
  "Initial"
);
const livenessOperationMode = ref<LivenessOperationMode>("PassiveActive");
const recognitionCondition = ref<boolean | undefined>();
const recognitionText = ref<string | undefined>();
const livenessCondition = ref<boolean>(false);
const livenessText = ref<string>("");
const errorMessage = ref<string>("");

function initFaceLivenessDetector(event: {
  file: File | undefined;
  livenessOperationMode: LivenessOperationMode;
}) {
  verifyImage.value = event.file;
  action.value = event.file ? "detectLivenessWithVerify" : "detectLiveness";
  livenessOperationMode.value = event.livenessOperationMode;
  livenessDetectorState.value = "LivenessDetector";
}

function displayResult(event: {
  recognitionCondition: boolean | undefined;
  recognitionText: string | undefined;
  livenessCondition: boolean;
  livenessText: string;
}) {
  recognitionCondition.value = event.recognitionCondition;
  recognitionText.value = event.recognitionText;
  livenessCondition.value = event.livenessCondition;
  livenessText.value = event.livenessText;
  livenessDetectorState.value = "Result";
}

function fetchFailureCallback(error: string) {
  errorMessage.value = `Failed to fetch the token. ${error}`;
  livenessDetectorState.value = "Retry";
}

function continueFaceLivenessDetector() {
  livenessDetectorState.value = "Initial";
}
</script>

<template>
  <InitialView
    v-if="livenessDetectorState === 'Initial'"
    @initFaceLivenessDetector="initFaceLivenessDetector"
  />
  <LivenessDetectorView
    v-if="livenessDetectorState === 'LivenessDetector'"
    :liveness-operation-mode="livenessOperationMode"
    :action="action"
    :file="verifyImage"
    @display-result="displayResult"
    @retry-liveness-detector="fetchFailureCallback"
  />
  <ResultView
    v-if="livenessDetectorState === 'Result'"
    :liveness-text="livenessText"
    :liveness-condition="livenessCondition"
    :recognition-text="recognitionText"
    :recognition-condition="recognitionCondition"
    @continue="continueFaceLivenessDetector"
  />
  <RetryView
    v-if="livenessDetectorState === 'Retry'"
    :error="errorMessage"
    @retry="continueFaceLivenessDetector"
  />
</template>

<style>
@import "../public/styles/fabric-9.6.1.min.css";

.page {
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
  min-width: 100%;
  margin: 0;
  overflow: hidden;
  overflow-y: auto;
  height: 100vh;
  display: flex;
  flex-direction: column;
}

body {
  margin: 0;
}
</style>

// samples/web/angularjs/src/app/app.component.ts
/* NOTE: This is an EXAMPLE app page for controlling the state of the app. This is not required to use the web component.
          For integration example, please see face-angularjs/src/face/liveness-detector-page.component.ts */

import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { LivenessOperationMode } from './utils';
import { NgIf } from '@angular/common';

// Components for different views based on state of the face liveness detector
import { InitialComponent } from './initial-page/initial-page.component';
import { FaceLivenessDetectorComponent } from '../face/liveness-detector-page.component';
import { ResultPageComponent } from './result-page/result-page.component';
import { RetryPageComponent } from './retry-page/retry-page.component';

type LivenessDetectorState = 'Initial' | 'LivenessDetector' | 'Result' | 'Retry';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    RouterOutlet,
    InitialComponent,
    FaceLivenessDetectorComponent,
    ResultPageComponent,
    RetryPageComponent,
    NgIf,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'face-angular';

  livenessDetectorState: LivenessDetectorState = 'Initial';

  // Face liveness detector parameters
  livenessOperationMode: LivenessOperationMode = 'PassiveActive';
  verifyImage: File | undefined;
  action: string = 'detectLiveness';

  // Retry display variables
  errorMessage: string | undefined;

  // Result display variables
  recognitionCondition: boolean | undefined;
  recognitionText: string | undefined;
  livenessCondition: boolean = false;
  livenessText: string = '';

  // View toggle
  pageHidden: { [key: string]: boolean } = {
    Initial: true,
    LivenessDetector: false,
    Result: false,
    Retry: false,
  };

  setLivenessDetectorState(s: LivenessDetectorState) {
    if (this.livenessDetectorState === s) {
      return;
    }
    this.pageHidden[this.livenessDetectorState] = false;
    this.livenessDetectorState = s;
    this.pageHidden[s] = true;
  }

  initFaceLivenessDetector(event: {
    livenessOperationMode: LivenessOperationMode;
    file: File | undefined;
  }) {
    this.verifyImage = event.file;
    this.action = event.file ? 'detectLivenessWithVerify' : 'detectLiveness';
    this.livenessOperationMode = event.livenessOperationMode;
    this.setLivenessDetectorState('LivenessDetector');
  }

  continueLivenessDetection() {
    this.setLivenessDetectorState('Initial');
  }

  displayResult(event: {
    recognitionCondition: boolean | undefined;
    recognitionText: string | undefined;
    livenessCondition: boolean;
    livenessText: string;
  }) {
    this.recognitionCondition = event.recognitionCondition;
    this.recognitionText = event.recognitionText;
    this.livenessCondition = event.livenessCondition;
    this.livenessText = event.livenessText;
    this.setLivenessDetectorState('Result');
  }

  fetchFailureCallback(error: string) {
    this.errorMessage = `Failed to fetch the token. ${error}`;
    this.setLivenessDetectorState('Retry');
  }
}

<main>
  <!-- Initial view of web app -->
  <initial-page
    *ngIf="pageHidden['Initial']"
    (initFaceLivenessDetector)="initFaceLivenessDetector($event)"
  ></initial-page>

  <!-- Face Liveness Detector view -->
  <liveness-detector-page
    *ngIf="pageHidden['LivenessDetector']"
    [livenessOperationMode]="livenessOperationMode"
    [action]="action"
    [file]="verifyImage"
    (retryFaceLivenessDetection)="fetchFailureCallback($event)"
    (displayResult)="displayResult($event)"
  ></liveness-detector-page>

  <!-- Result display view -->
  <result-page
    *ngIf="pageHidden['Result']"
    [livenessCondition]="livenessCondition"
    [livenessText]="livenessText"
    [recognitionCondition]="recognitionCondition"
    [recognitionText]="recognitionText"
    (continueLivenessDetection)="continueLivenessDetection()"
  ></result-page>

  <!-- Retry display view (in case of token generation failure) -->
  <retry-page
    *ngIf="pageHidden['Retry']"
    [errorMessage]="errorMessage"
    (retryFaceLivenessDetection)="continueLivenessDetection()"
  ></retry-page>
</main>
